# Generated by Django 5.0.7 on 2024-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid',
            field=models.DateField(),
        ),
    ]
