# Generated by Django 5.0.7 on 2024-08-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='festival_virgin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.attendee'),
        ),
    ]
