# Generated by Django 5.0.7 on 2024-07-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid',
        ),
    ]
