# Generated by Django 5.0.7 on 2024-09-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='expenses.attendee'),
        ),
    ]
