# Generated by Django 5.0.7 on 2024-07-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.attendee'),
        ),
    ]
