# Generated by Django 5.0.7 on 2024-07-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.expense')),
            ],
            bases=('expenses.expense',),
        ),
        migrations.CreateModel(
            name='ElectricExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.expense')),
            ],
            bases=('expenses.expense',),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('ELECTRIC', 'Electric'), ('CAMPING', 'Camping')], default='CAMPING', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.attendee'),
        ),
    ]
